version: "3.8"

services:
  bot:
    build: .
    image: discord-ai-app:latest
    container_name: discord-ai-app
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LLM_PROVIDER=https://api.openai.com/v1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_TEMPERATURE=0.1
      - DISCORD_BOT_MODEL=gpt-6-sol

    restart: unless-stopped
